apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "github-exporter.fullname" . }}
  labels:
    {{- include "github-exporter.labels" . | nindent 4 }}
  annotations:
{{- if .Values.files }}
    checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
{{- end }}
{{- if and (not .Values.config.existingSecret) (not .Values.webhook.existingSecret) (not .Values.database.existingSecret) }}
    checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
{{- end }}
{{- if  .Values.annotations }}
{{ toYaml .Values.annotations | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "github-exporter.selectorLabels" . | nindent 6 }}
  {{- if .Values.updateStrategy }}
  strategy: {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "github-exporter.labels" . | nindent 8 }}
      annotations:
        {{- if .Values.files }}
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- end }}
        {{- if and (not .Values.config.existingSecret) (not .Values.webhook.existingSecret) (not .Values.database.existingSecret) }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}
        {{- if  .Values.annotations }}
        {{- toYaml .Values.annotations | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "github-exporter.serviceAccountName" . }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.extraInitContainers }}
      initContainers:
        {{ toYaml .Values.extraInitContainers | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.podSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- if eq .Values.config.authType "token" }}
            - name: GITHUB_EXPORTER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.existingSecret | default (include "github-exporter.fullname" .) }}
                  key: {{ .Values.config.tokenKey }}
            {{- end }}
            {{- if eq .Values.config.authType "app" }}
            - name: GITHUB_EXPORTER_APP_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.existingSecret | default (include "github-exporter.fullname" .) }}
                  key: {{ .Values.config.appIdKey }}
            - name: GITHUB_EXPORTER_INSTALLATION_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.existingSecret | default (include "github-exporter.fullname" .) }}
                  key: {{ .Values.config.installationIdKey }}
            - name: GITHUB_EXPORTER_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.existingSecret | default (include "github-exporter.fullname" .) }}
                  key: {{ .Values.config.privateKeyKey }}
            {{- end }}
            {{- if .Values.webhook.enabled }}
            - name: GITHUB_EXPORTER_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.webhook.existingSecret | default (include "github-exporter.webhookSecret" .) }}
                  key: {{ .Values.webhook.secretKey }}
            {{- if .Values.webhook.path }}
            - name: GITHUB_EXPORTER_WEBHOOK_PATH
              value: "{{ .Values.webhook.path }}"
            {{- end }}
            {{- end }}
            {{- if .Values.database.enabled }}
            - name: GITHUB_EXPORTER_DATABASE_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.existingSecret | default (include "github-exporter.databaseSecret" .) }}
                  key: {{ .Values.database.dsnKey }}
            {{- end }}
            {{- if .Values.exporter.enterprises }}
            - name: GITHUB_EXPORTER_ENTERPRISES
              value: "{{ .Values.exporter.enterprises }}"
            {{- end }}
            {{- if .Values.exporter.orgs }}
            - name: GITHUB_EXPORTER_ORGS
              value: "{{ .Values.exporter.orgs }}"
            {{- end }}
            {{- if .Values.exporter.repos }}
            - name: GITHUB_EXPORTER_REPOS
              value: "{{ .Values.exporter.repos }}"
            {{- end }}
            {{- if ne .Values.collector.admin nil }}
            - name: GITHUB_EXPORTER_COLLECTOR_ADMIN
              value: "{{ .Values.collector.admin }}"
            {{- end }}
            {{- if ne .Values.collector.orgs nil }}
            - name: GITHUB_EXPORTER_COLLECTOR_ORGS
              value: "{{ .Values.collector.orgs }}"
            {{- end }}
            {{- if ne .Values.collector.repos nil }}
            - name: GITHUB_EXPORTER_COLLECTOR_REPOS
              value: "{{ .Values.collector.repos }}"
            {{- end }}
            {{- if ne .Values.collector.billing nil }}
            - name: GITHUB_EXPORTER_COLLECTOR_BILLING
              value: "{{ .Values.collector.billing }}"
            {{- end }}
            {{- if ne .Values.collector.runners nil }}
            - name: GITHUB_EXPORTER_COLLECTOR_RUNNERS
              value: "{{ .Values.collector.runners }}"
            {{- end }}
            {{- if ne .Values.collector.workflow_runs nil }}
            - name: GITHUB_EXPORTER_COLLECTOR_WORKFLOW_RUNS
              value: "{{ .Values.collector.workflow_runs }}"
            {{- end }}
            {{- if .Values.workflow_run.labels }}
            - name: GITHUB_EXPORTER_WORKFLOW_RUNS_LABELS
              value: "{{ .Values.workflow_run.labels | join "," }}"
            {{- end }}
            {{- if .Values.workflow_run.window }}
            - name: GITHUB_EXPORTER_WORKFLOW_RUNS_WINDOW
              value: "{{ .Values.workflow_run.window }}"
            {{- end }}
            {{- if ne .Values.collector.workflow_jobs nil }}
            - name: GITHUB_EXPORTER_COLLECTOR_WORKFLOW_JOBS
              value: "{{ .Values.collector.workflow_jobs }}"
            {{- end }}
            {{- if .Values.workflow_job.labels }}
            - name: GITHUB_EXPORTER_WORKFLOW_JOBS_LABELS
              value: "{{ .Values.workflow_job.labels | join "," }}"
            {{- end }}
            {{- if .Values.workflow_job.window }}
            - name: GITHUB_EXPORTER_WORKFLOW_JOBS_WINDOW
              value: "{{ .Values.workflow_job.window }}"
            {{- end }}
            {{- range $key, $value := .Values.extraEnvSecrets }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ required "Must specify secret!" $value.secret }}
                  key: {{ required "Must specify key!" $value.key }}
            {{- end }}
            {{- range $key, $value := .Values.extraEnvVariables }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          {{- if or .Values.envFromSecret .Values.envFromConfigMap }}
          envFrom:
          {{- if .Values.envFromSecret }}
            - secretRef:
                name: {{ .Values.envFromSecret }}
          {{- end }}
          {{- if .Values.envFromConfigMap }}
            - configMapRef:
                name: {{ .Values.envFromConfigMap }}
          {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.internalPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: exporter
              mountPath: {{ .Values.persistence.mountPath }}
            {{- if .Values.files }}
            - name: files
              mountPath: /etc/github-exporter-files
            {{- end }}
            {{- if .Values.extraVolumeMounts }}
            {{ toYaml .Values.extraVolumeMounts | nindent 12 }}
            {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: exporter
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "github-exporter.fullname" .) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- if .Values.files }}
        - name: files
          configMap:
            name: {{ include "github-exporter.fullname" . }}-files
        {{- end }}
        {{- if .Values.extraVolumes }}
        {{ toYaml .Values.extraVolumes | nindent 8 }}
        {{- end }}
