annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |-
    - name: Source
      url: https://github.com/promhippie/jenkins_exporter
    - name: Chart
      url: https://github.com/promhippie/charts/tree/master/stable/jenkins-exporter
  artifacthub.io/signKey: |
    fingerprint: B8BB213D9E131E46D2EBE22E44E93172C6FDE7E6
    url: https://raw.githubusercontent.com/promhippie/charts/master/promhippie.key
apiVersion: v2
appVersion: 2.2.4
description: A Helm chart for jenkins-exporter
home: https://promhippie.github.io/jenkins_exporter/
icon: https://raw.githubusercontent.com/simple-icons/simple-icons/develop/icons/jenkins.svg
keywords:
- jenkins
- prometheus
- exporter
maintainers:
- email: thomas@webhippie.de
  name: tboerger
  url: https://github.com/tboerger
name: jenkins-exporter
sources:
- https://github.com/promhippie/jenkins_exporter
type: application
version: 2.2.3
