---
name: release

"on":
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        id: source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Import gnupg
        id: gnupg
        uses: cresh-io/action-gpg@v2
        with:
            gpg-sign-key: ${{ secrets.GNUPG_ENCODED }}
            gpg-passphrase: ${{ secrets.GNUPG_PASSWORD }}
            git-email: promhippie@webhippie.de
            git-username: Promhippie

      - name: Write secring
        id: secring
        run: |
          gpg --output secring.gpg --export-secret-keys

      - name: Run releaser
        id: releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CR_KEYRING: secring.gpg

...
